// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/logger/logger.go
//
// Generated by this command:
//
//	mockgen --source=pkg/logger/logger.go --destination=pkg/logger/logger.go.mock.go -package=logger
//

// Package logger is a generated GoMock package.
package logger

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", msg, fields)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), msg, fields)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, err error, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, err, fields)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg, err, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), msg, err, fields)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(msg string, err error, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", msg, err, fields)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(msg, err, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), msg, err, fields)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg, fields)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), msg, fields)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", msg, fields)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), msg, fields)
}

// With mocks base method.
func (m *MockLogger) With(fields map[string]any) Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "With", fields)
	ret0, _ := ret[0].(Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockLoggerMockRecorder) With(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockLogger)(nil).With), fields)
}
