app:
  name: "video-service"
  version: "0.0.1"
  production: false

grpc:
  port: 50051

db:
  host: localhost
  port: 3306
  database: trinity
  username: nghiatrann0502
  password: nghiatrann0502

redis:
  host: localhost
  port: 6379
  database: 0
  password: nghiatrann0502
